# Generated by Django 4.0.3 on 2022-04-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_created_at_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurer', models.CharField(max_length=200, null=True)),
                ('product', models.CharField(max_length=200, null=True)),
                ('policy_number', models.IntegerField(max_length=200, null=True)),
                ('renewal', models.DateField()),
                ('policy_yearly', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
